name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create environment directory
        run: mkdir -p src/environments
        
      - name: Create environment file
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: true," >> src/environments/environment.ts
          echo "  firebase: {" >> src/environments/environment.ts
          echo "    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> src/environments/environment.ts
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> src/environments/environment.ts
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/environments/environment.ts
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> src/environments/environment.ts
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> src/environments/environment.ts
          echo "    app_release_date: '${{ github.event.head_commit.timestamp }}'," >> src/environments/environment.ts
          echo "    app_release_version: '${{ github.sha }}'," >> src/environments/environment.ts
          echo "  }" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts
          
      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: Deploy to GitHub Pages
        run: ng deploy --base-href=/SelfServiceDesk/