name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Create environment directory
        run: mkdir -p src/environments

      - name: Create environment file
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  firebase: {" >> src/environments/environment.prod.ts
          echo "    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> src/environments/environment.prod.ts
          echo "    appId: '${{ secrets.FIREBASE_APP_ID }}'," >> src/environments/environment.prod.ts
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> src/environments/environment.prod.ts
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/environments/environment.prod.ts
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> src/environments/environment.prod.ts
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'" >> src/environments/environment.prod.ts
          echo "  }," >> src/environments/environment.prod.ts
          echo "  app_release_date: '${{ github.event.head_commit.timestamp }}'," >> src/environments/environment.prod.ts
          echo "  app_release_version: '${{ github.sha }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: ng build --configuration production

      - name: Create .nojekyll file
        run: touch dist/self-service-desk/browser/.nojekyll

      - name: Deploy to GitHub Pages
        run: ng deploy --project=selfservicedesk --no-silent
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          APP_RELEASE_DATE: ${{ github.event.head_commit.timestamp }}
          APP_RELEASE_VERSION: ${{ github.sha }}
